#!/usr/bin/env bash

# Program version
VERSION="v1.0"

# Define colors
COLOR_BLACK="\033[0;30m"
COLOR_RED="\033[0;31m"
COLOR_GREEN="\033[0;32m"
COLOR_ORANGE="\033[0;33m"
COLOR_BLUE="\033[0;34m"
COLOR_PURPLE="\033[0;35m"
COLOR_CYAN="\033[0;36m"
COLOR_LIGHT_GRAY="\033[0;37m"
COLOR_DARK_GRAY="\033[1;30m"
COLOR_LIGHT_RED="\033[1;31m"
COLOR_LIGHT_GREEN="\033[1;32m"
COLOR_YELLOW="\033[1;33m"
COLOR_LIGHT_BLUE="\033[1;34m"
COLOR_LIGHT_PURPLE="\033[1;35m"
COLOR_LIGHT_CYAN="\033[1;36m"
COLOR_WHITE="\033[1;37m"

# Define some "special" sequences
COLOR_NONE="\033[0m"
CLEAR_LINE="\033[1K\033[1000D"

########################
# Check for parameters #
########################

if [ "$1" ]; then  # Parameter given?
  if [ "$1" = "--help" ]; then
    echo "Usage: shrinkpdf [OPTIONS] FILES"
    echo
    echo "shrinkpdf will shrink the given PDF."
    echo
    echo "Options"
    echo "--help     This help"
    exit 0
  fi
fi

##########################
# Check for needed tools #
##########################

NEEDED_TOOLS="mv gs awk tr"

for x in $NEEDED_TOOLS; do
  which $x > /dev/null
  if [ $? -ne 0 ]; then
    echo -e "Tool $COLOR_WHITE$x$COLOR_NONE is missing!"
    exit 1
  fi
done

###############
# Starting up #
###############

echo -ne "$COLOR_LIGHT_RED"
echo


echo "     _                      ____  _          _       _    ____  ____  _____ "
echo "  __| | ___  _ __ ___   ___/ ___|| |__  _ __(_)_ __ | | _|  _ \|  _ \|  ___|"
echo " / _\` |/ _ \| '_ \` _ \ / _ \___ \| '_ \| '__| | '_ \| |/ / |_) | | | | |_   "
echo "| (_| | (_) | | | | | | (_) |__) | | | | |  | | | | |   <|  __/| |_| |  _|  "
echo " \__,_|\___/|_| |_| |_|\___/____/|_| |_|_|  |_|_| |_|_|\_\_|   |____/|_|    "
echo -e "$COLOR_RED""domoShrinkPDF $COLOR_LIGHT_RED$VERSION"
echo -ne "$COLOR_NONE"
echo

###########
# Prepare #
###########

# Start time
echo -e "Starting $COLOR_LIGHT_PURPLE$(date '+%Y-%m-%d %H:%M:%S')$COLOR_NONE"
START=$(date '+%s')

################
# Rename Files #
################

FILECOUNT=$#
FILENUM=0
for INPUTFILE in "$@"; do
  # Get name parts of old file
  FILENAME="${INPUTFILE##*/}"
  DIRECTORY="${INPUTFILE:0:${#INPUTFILE} - ${#FILENAME}}"
  BASENAME="${INPUTFILE%.[^.]*}"
  EXTENSION=$(echo "${INPUTFILE:${#BASENAME} + 1}" | tr [:upper:] [:lower:])

  #echo "Inputfile: $INPUTFILE"
  #echo "Filename:  $FILENAME"
  #echo "Directory: $DIRECTORY"
  #echo "Basename:  $BASENAME"
  #echo "Extension: $EXTENSION"

  # Handle file shrinking
  FILENUM=$((FILENUM+1))
  echo -ne "$COLOR_YELLOW[$FILENUM/$FILECOUNT]$COLOR_NONE "

  if [ "$EXTENSION" == "pdf" ]; then
    OUTPUTFILE="$BASENAME.shrinked.pdf"
    echo -e "Shrinking $COLOR_WHITE'"$(basename "$INPUTFILE")"'$COLOR_NONE to $COLOR_WHITE'"$(basename "$OUTPUTFILE")"'$COLOR_NONE"
    gs -sDEVICE=pdfwrite -dPDFSETTINGS=/ebook -q -o "$OUTPUTFILE" "$INPUTFILE"
  else
    echo -e "$COLOR_WHITE'"$INPUTFILE"'$COLOR_LIGHT_RED has a wrong extension!$COLOR_NONE"
  fi
done

################
# Finishing up #
################

echo -e "Finished $COLOR_LIGHT_PURPLE$(date '+%Y-%m-%d %H:%M:%S')$COLOR_NONE"
END=$(date '+%s')
echo -e "Prog took $COLOR_LIGHT_PURPLE$(( $END - $START )) seconds$COLOR_NONE"
